# workflow for testing
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test-webserver:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: set up mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '9.0.1'
        mysql database: 'email_donations'
        mysql user: 'donor'
        mysql password: ${{ secrets.MYSQL_PASSWORD }} 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: run base tests
      env:
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      run: |
        cd src/app
        python -m pytest -svv --cov=. --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}