# workflow for e2e tests
name: frontend-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test-frontend:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Install dependencies
          run: |
            cd src/app/frontend 
            pnpm install
        - name: Install Playwright Browsers
          run: pnpx playwright install --with-deps
        - name: Run Playwright tests
          run: pnpx test
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30